[[plugins]]
repo = 'Shougo/neomru.vim'
on_if = 1

 [[plugins]]
repo = 'Shougo/neocomplete.vim'
depends = 'context_filetype.vim'
if = "has('lua')"
on_event = 'InsertEnter'

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets', 'context_filetype.vim']
on_event = 'InsertCharPre'
on_ft = 'snippet'
hook_source = 'source ~/.vim/rc/plugins/neosnippet.rc.vim'

# ファイルのアウトライン表示
[[plugins]]
repo = 'Shougo/unite-outline'
on_source = 'unite.vim'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

# C#コーディング支援
[[plugins]]
repo = 'OmniSharp/omnisharp-vim'
on_path = ['*.cs','*.csi', '*.csx', '*.ipy']
hook_post_update = '''
if dein#util#_is_windows()
    let cmd = 'msbuild server/OmniSharp.sln'
  elseif dein#util#_is_mac()
    let cmd  = 'xbuild server/OmniSharp.sln'
  else
    let cmd = 'xbuild server/OmniSharp.sln'
  endif
  let g:dein#plugin.build = cmd
'''

# コードの実行
[[plugins]]
repo = 'thinca/vim-quickrun'
on_map = [['n', '<Plug>']]
hook_add = 
'''
  nmap <silent> <Leader>r <Plug>(quickrun)
  let g:quickrun_config = {
    \ "*": {"runner": "vimproc"},
    \ }
'''

# Python支援
[[plugins]]
repo = "davidhalter/jedi-vim"
hook_add = '''
  " jediにvimの設定を任せると'completeopt+=preview'するので
  " 自動設定機能をOFFにし手動で設定を行う
  let g:jedi#auto_vim_configuration = 0
  " 補完の最初の項目が選択された状態だと使いにくいためオフにする
  let g:jedi#popup_select_first = 0
  " quickrunと被るため大文字に変更
  let g:jedi#rename_command = '<Leader>R'
'''

# Tomlシンタックス
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'
