[[plugins]]
repo = 'Shougo/neomru.vim'
on_if = 1

 [[plugins]]
repo = 'Shougo/neocomplete.vim'
depends = 'context_filetype.vim'
if = "has('lua')"
on_event = 'InsertEnter'

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets', 'context_filetype.vim']
on_event = 'InsertCharPre'
on_ft = 'snippet'
hook_source = 'source ~/.vim/rc/plugins/neosnippet.rc.vim'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'OmniSharp/omnisharp-vim'
on_path = ['*.cs','*.csi', '*.csx', '*.ipy']
hook_post_update = '''
if dein#util#_is_windows()
    let cmd = 'msbuild server/OmniSharp.sln'
  elseif dein#util#_is_mac()
    let cmd  = 'xbuild server/OmniSharp.sln'
  else
    let cmd = 'xbuild server/OmniSharp.sln'
  endif
  let g:dein#plugin.build = cmd
'''
